# -*- coding: utf-8 -*-
"""NN assgn1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C0e5Q__UHU3OJJAlxiteFHmB1sLC7yLl
"""

import matplotlib.pyplot as plt

x = []
for i in range(-10,11):
  x.append(i)
x

#linear y=f(x)=x

y=x
plt.plot(x,y)

# bilinear  y= {0 if x<0 , 1 if x>=0} ie theta is 0
y=[]
for i in x:
  if i<0:
    y.append(0)
  else:
    y.append(1)
plt.plot(x,y)

#binary sigmoidal
import math
y=[]
for i in x:
  v = 1/(1+math.exp(-i)) #sigma =1
  y.append(v)
print(y)
plt.plot(x,y)

#biploar sigmoid
y=[]
for i in x:
  v=(1-math.exp(-i))/(1+math.exp(-i))
  y.append(v)
plt.plot(x,y)

